### ISSUE TITLE
Inputs within components within dialog not receiving focus

### ISSUE THREAD

**Issue by akc42** [GoogleChrome/dialog-polyfill#189]
I have a dialog which contains components (as subclassed lit-element elements) which them selves contain <input> elements.  I have registered the dialogs and open them with Show Modal, but when I try and click on the input field that is displayed it doesn't accept focus. So I can't edit the input field (and on an ipad the on screen keyboard never comes up).

I am trying to test this on a mac running safari - 

This all works perfectly in Chrome (on a non Apple platform).

**Comment by hadriann** [comment]
Indeed this seems to be a bug in the polyfill. Due to event retargeting in shadow DOM, the event target in the "focus" listener is not the focused element itself, but the custom element host. Thus, the event listener should use the event composed path when available instead of the event target.

**Comment by samthor** [comment]
Thanks, I'll look soon.

**Comment by hadriann** [comment]
@samthor if you want, I can open a PR for this one.

**Comment by kwaclaw** [comment]
Just ran into the same issue on Firefox. Dialog with form inside works perfectible in Chrome and Chromium based Edge, but in Firefox all text inputs are unusable, as they don't get focus. It looks like the polyfill that does not take shadow dom into account in all the places where it should.

**Comment by hadriann** [comment]
@samthor please take a look at PR #198 that should solve this.

**Comment by kwaclaw** [comment]
I tried this fix but I still can't get the text inputs in Firefox to focus.

**Comment by samthor** [comment]
Would love to see a repro case for Firefox.

**Comment by ar2r13** [comment]
Inputs are still unavailable in safari(

**Comment by gustavosmonteiro** [comment]
I'm having this issue also with Firefox and IE11. When I have a dialog inside another dialog, the second one can't get focus on the inputs inside it.

**Comment by hadriann** [comment]
@samthor - the issue seems to be with calling `safeBlur` inside `dialogPolyfill.DialogManager.prototype.handleFocus_`. When focusing a form element, it's immediately blurred. Any idea why it's getting called there? Anyway, it seems that in latest versions of Firefox and Safari, `document.activeElement` takes into account any focused element in the shadow DOM.

**Comment by hadriann** [comment]
> @samthor - the issue seems to be with calling `safeBlur` inside `dialogPolyfill.DialogManager.prototype.handleFocus_`. When focusing a form element, it's immediately blurred. Any idea why it's getting called there? Anyway, it seems that in latest versions of Firefox and Safari, `document.activeElement` takes into account any focused element in the shadow DOM.

As far as I can see, `safeBlur` tries to prevent focusing elements that are outside a dialog - which is a good intention. So for each element that is about to receive focus, some checks are done to see if that element is inside a dialog. Those checks start from the given element and traverse up the DOM tree from parent to parent. It works well in regular DOM, but fails in shadow DOM because `element.parentElement` returns `null` when the parent element is a shadow root. In this case, `element.parentNode.host` should be used instead.

@samthor - I've addressed this in PR #213 and I'd appreciate if you could take a look at it.

**Comment by samthor** [comment]
@hadriann thanks for the fix. I'll publish today.

**Comment by hadriann** [comment]
@samthor thanks, would be great if it's published today!

**Comment by samthor** [comment]
Done, sorry for the delay.
